---
- name: Debian 12 Post-Installation Configuration
  hosts: all
  remote_user: "{{ ansible_user | default('real') }}"  # Connect as regular user
  become: yes
  become_method: su     # Use 'su' instead of 'sudo' since sudo isn't installed
  become_user: root
  gather_facts: no      # Skip facts gathering initially
  vars:
    regular_user: "real"  # Change this to your desired username
    
  tasks:
    - name: Install python3 if not present (raw command)
      raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          apt update && apt install -y python3
        fi
      changed_when: false

    - name: Gather facts now that python3 is available
      setup:
    - name: Comment out CDROM sources in apt sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb cdrom'
        line: '#\g<0>'
        backrefs: yes
      notify: update apt cache

    - name: Update apt cache
      apt:
        update_cache: yes
      tags: packages

    - name: Install essential packages
      apt:
        name:
          - sudo
          - unzip
        state: present
        update_cache: yes
      tags: packages

    - name: Ensure the regular user exists
      user:
        name: "{{ regular_user }}"
        state: present
        shell: /bin/bash
        create_home: yes
      tags: user_setup

    - name: Add user to sudo group
      user:
        name: "{{ regular_user }}"
        groups: sudo
        append: yes
      tags: user_setup

    - name: Configure sudo access for the user (without validation first)
      lineinfile:
        path: /etc/sudoers
        line: "{{ regular_user }}  ALL=(ALL:ALL) ALL"
        regexp: "^{{ regular_user }}\\s"
        backup: yes
      tags: sudo_config

    - name: Validate sudoers file after modification
      command: /usr/sbin/visudo -c
      register: sudoers_valid
      changed_when: false
      tags: sudo_config

    - name: Display sudoers validation result
      debug:
        msg: "Sudoers file validation: {{ sudoers_valid.stdout }}"
      tags: sudo_config

    - name: Verify sudo configuration
      command: sudo -l -U {{ regular_user }}
      register: sudo_check
      changed_when: false
      tags: verification

    - name: Display sudo privileges for user
      debug:
        msg: "Sudo privileges for {{ regular_user }}: {{ sudo_check.stdout_lines }}"
      tags: verification

    - name: Switch context to regular user for verification
      debug:
        msg: "Configuration complete. User '{{ regular_user }}' can now use sudo. You can now switch to this user with 'su {{ regular_user }}'"

  handlers:
    - name: update apt cache
      apt:
        update_cache: yes
